### ISSUE TITLE
main.c:14:10: fatal error: xc.h: No such file or directory

### ISSUE THREAD

**Issue by moricef** [ServError/Thrustmaster_Warthog_Throttle_Alps_Slew_Mod#1]
Hi, and thank you for your work.
I'm not a great programmer and I tried since several weeks hardly to make a I2C slave code with arduino IDE based on the I2C master code by Mike Hord from SparkFun for the AMS N35P112 (http://cdn.sparkfun.com/datasheets/BreakoutBoards/EasyPoint_Demo.ino) and having read, not all,  the N35P112 datasheet. But I have somes difficulty with the Wire library and the slave handlers.
And tonight, I find your project ...
So I try to compile it with Geany under Linux, but there is that fatal error with that included header xc.h
I have installed all the necessary for the avr-c with linux : avrdude gcc-avr avr-libc

**Comment by ServError** [comment]
This project was built in Microchip Studio with the XC8 toolchain, which your setup lacks and therefor errors out.

You can most likely replace the line including xc.h and instead include avr/io.h and build in your current environment.

**Comment by moricef** [comment]
Thanks. It's ok now. 
Would you be able to detail your code explanations in the comments in order to make it more understandable for non-experts like me. For an educational purpose.
For example, why the files twi_slave.h and twi_slave.c (AVR290: Avoid Clock Stretch with Tiny AVR)?
Or even the whole preparation part of the registers of the ATtiny441, (ADC, Pull-up resistances, timers, interruptions, etc.)

**Comment by Shawnb03** [comment]
I am completely lost to what I need to do to program the attiny441 IC. Could you please guide me on what I need to do to program it. I have all the other parts listed except for the PCB and those come in on the 21st. Your help would be greatly appreciated.

**Comment by ServError** [comment]
> I am completely lost to what I need to do to program the attiny441 IC. Could you please guide me on what I need to do to program it. I have all the other parts listed except for the PCB and those come in on the 21st. Your help would be greatly appreciated.

Hi. Please don't append new issues to someone else's existing closed issue, the chance of it being seen is slim. If you're still having trouble, open a new issue. Thanks.
